name: responsive_toolkit
description: Easy-to-use responsive tools for Flutter. Simplify layouts across screens of any size and shape.
version: 0.0.4
homepage: https://github.com/Calpoog/responsive_toolkit

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  golden_toolkit: ^0.9.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    # needed to trigger the FontManifest.json to be included
    - images/
