name: flutter_responsive
description: Responsive layout tools for Flutter
version: 0.0.1
homepage: https://github.com/Calpoog/flutter_responsive

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
