name: responsive_toolkit
description: Easy-to-use responsive tools for Flutter. Simplify layouts across screens of any size and shape.
version: 0.0.1
homepage: https://github.com/Calpoog/responsive_toolkit

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
